name: LLM
dependencies:
  - annotated-types=0.7.0
  - anyio=4.9.0
  - bzip2=1.0.8
  - ca-certificates=2025.7.9
  - certifi=2025.7.9
  - colorama=0.4.6
  - distro=1.9.0
  - exceptiongroup=1.3.0
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.10
  - jiter=0.10.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - liblzma=5.8.1
  - libsqlite=3.50.2
  - libzlib=1.3.1
  - ncurses=6.5
  - openai=1.95.0
  - openssl=3.5.1
  - pip=25.1.1
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - python=3.12.11
  - python_abi=3.12
  - readline=8.2
  - setuptools=80.9.0
  - sniffio=1.3.1
  - tk=8.6.13
  - tqdm=4.67.1
  - typing-extensions=4.14.1
  - typing-inspection=0.4.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - wheel=0.45.1